stages:
  - build
  - generate
  - install
  - test
variables:
  PLAYWRIGHT_BROWSERS_PATH: $CI_PROJECT_DIR/browsers

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - browsers/  # 缓存浏览器安装目录
  policy: pull-push

build-dependencies:
  stage: build
  script:
    - npm ci
    - npx playwright install  # 安装所有必需的浏览器

generate-config:
  stage: generate
  script:
    - npm run generator
  artifacts:
    paths:
      - dynamic-config.yml
    expire_in: 1 hour  # 根据需要调整过期时间
  tags:
    - windows

trigger-child:
  stage: install
  trigger:
    include: dynamic-config.yml

