stages:
  - build
  - generate
  - test

build-dependencies:
  stage: build
  script: npm ci
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push

generate-config:
  stage: generate
  script:
    - npm run generator
  artifacts:
    paths:
      - dynamic-config.yml
    expire_in: 1 hour  # 根据需要调整过期时间
  tags:
    - windows

trigger-child:
  stage: test
  trigger:
    include: dynamic-config.yml

