stages:
  - generate
  - test

generate-config:
  stage: generate
  script:
    - node generator.js
  artifacts:
    paths:
      - dynamic-config.yml
  tags:
    - windows

trigger-child:
  stage: test
  trigger:
    include: dynamic-config.yml

