stages:
  - install
  - test
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - browsers/
  policy: pull-push
variables:
  PLAYWRIGHT_BROWSERS_PATH: $CI_PROJECT_DIR/browsers
install-browser:
  stage: install
  script:
    - npx playwright install
playwright_test_4fbcce102fd8e8853f70fb81a5b50f28:
  stage: test
  script:
    - >-
      npx playwright test tests/test1.test.ts
      --output=./reports/report_4fbcce102fd8e8853f70fb81a5b50f28.json
  tags:
    - windows
playwright_test_a4ccd4a563e0a7d69c87165f689df0d6:
  stage: test
  script:
    - >-
      npx playwright test tests/test2.test.ts
      --output=./reports/report_a4ccd4a563e0a7d69c87165f689df0d6.json
  tags:
    - windows
playwright_test_b391019884a3d9117a40995b6ab0e1df:
  stage: test
  script:
    - >-
      npx playwright test tests/test3.test.ts
      --output=./reports/report_b391019884a3d9117a40995b6ab0e1df.json
  tags:
    - windows
playwright_test_daaa57b58eab3c369f31bf9cf08eacbf:
  stage: test
  script:
    - >-
      npx playwright test tests/test4.test.ts
      --output=./reports/report_daaa57b58eab3c369f31bf9cf08eacbf.json
  tags:
    - windows
playwright_test_9df8843fe8505907b335e4c0c47616c1:
  stage: test
  script:
    - >-
      npx playwright test tests/test5.test.ts
      --output=./reports/report_9df8843fe8505907b335e4c0c47616c1.json
  tags:
    - windows
playwright_test_cd9e362aad6008978be55a933bdd1321:
  stage: test
  script:
    - >-
      npx playwright test tests/test6.test.ts
      --output=./reports/report_cd9e362aad6008978be55a933bdd1321.json
  tags:
    - windows
playwright_test_b008e8078de93d37f371f7ff4e8570c7:
  stage: test
  script:
    - >-
      npx playwright test tests/test7.test.ts
      --output=./reports/report_b008e8078de93d37f371f7ff4e8570c7.json
  tags:
    - windows
playwright_test_98f7404eb2004f5722a918dc857c22dd:
  stage: test
  script:
    - >-
      npx playwright test tests/test8.test.ts
      --output=./reports/report_98f7404eb2004f5722a918dc857c22dd.json
  tags:
    - windows
