stages:
  - install
  - test
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - browsers/
  policy: pull-push
variables:
  PLAYWRIGHT_BROWSERS_PATH: $CI_PROJECT_DIR/browsers
install-browser:
  stage: install
  script:
    - npx playwright install
artifacts:
  paths:
    - node_modules/
    - browsers/
  expire_in: 1 hour
playwright_test_cd2e96fe74074a4fe14301e9b7348b3b:
  stage: test
  script:
    - >-
      npx playwright test tests/test1.test.ts --reporter=json 
      --output=./reports/report_cd2e96fe74074a4fe14301e9b7348b3b.json
  tags:
    - windows
playwright_test_7e19daf462b3e01813620e2d63806191:
  stage: test
  script:
    - >-
      npx playwright test tests/test2.test.ts --reporter=json 
      --output=./reports/report_7e19daf462b3e01813620e2d63806191.json
  tags:
    - windows
playwright_test_f0e89916640ec11ec076d1189ea2cc0f:
  stage: test
  script:
    - >-
      npx playwright test tests/test3.test.ts --reporter=json 
      --output=./reports/report_f0e89916640ec11ec076d1189ea2cc0f.json
  tags:
    - windows
playwright_test_b2f99d109beb7b7ee85bd66741514207:
  stage: test
  script:
    - >-
      npx playwright test tests/test4.test.ts --reporter=json 
      --output=./reports/report_b2f99d109beb7b7ee85bd66741514207.json
  tags:
    - windows
playwright_test_ea1e49cfdb2562534be98ca4acda6da3:
  stage: test
  script:
    - >-
      npx playwright test tests/test5.test.ts --reporter=json 
      --output=./reports/report_ea1e49cfdb2562534be98ca4acda6da3.json
  tags:
    - windows
playwright_test_7e65e1a54216937f62618771961064b4:
  stage: test
  script:
    - >-
      npx playwright test tests/test6.test.ts --reporter=json 
      --output=./reports/report_7e65e1a54216937f62618771961064b4.json
  tags:
    - windows
playwright_test_13eede077b8cddf070cbf4fc6ce761c3:
  stage: test
  script:
    - >-
      npx playwright test tests/test7.test.ts --reporter=json 
      --output=./reports/report_13eede077b8cddf070cbf4fc6ce761c3.json
  tags:
    - windows
playwright_test_646dbafb0f202290c004e6237020544a:
  stage: test
  script:
    - >-
      npx playwright test tests/test8.test.ts --reporter=json 
      --output=./reports/report_646dbafb0f202290c004e6237020544a.json
  tags:
    - windows
