stages:
  - install
  - test
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - browsers/
  policy: pull-push
variables:
  PLAYWRIGHT_BROWSERS_PATH: $CI_PROJECT_DIR/browsers
install-browser:
  stage: install
  script:
    - npx playwright install
  tags:
    - windows
playwright_test_5e465037bca1e2f11ad6ddc1730b1cbd:
  stage: test
  script:
    - >-
      npx playwright test tests/test1.test.ts
      --output=./reports/report_5e465037bca1e2f11ad6ddc1730b1cbd.json
  tags:
    - windows
playwright_test_87ccb6ac49e07d5526f904514531f486:
  stage: test
  script:
    - >-
      npx playwright test tests/test2.test.ts
      --output=./reports/report_87ccb6ac49e07d5526f904514531f486.json
  tags:
    - windows
playwright_test_ffc2792b98c3363a297fe2d90fca04c7:
  stage: test
  script:
    - >-
      npx playwright test tests/test3.test.ts
      --output=./reports/report_ffc2792b98c3363a297fe2d90fca04c7.json
  tags:
    - windows
playwright_test_2c324808d46b34ef45ffe96dd0126f82:
  stage: test
  script:
    - >-
      npx playwright test tests/test4.test.ts
      --output=./reports/report_2c324808d46b34ef45ffe96dd0126f82.json
  tags:
    - windows
playwright_test_da0566a24ff0cbebccd677f4baeca5da:
  stage: test
  script:
    - >-
      npx playwright test tests/test5.test.ts
      --output=./reports/report_da0566a24ff0cbebccd677f4baeca5da.json
  tags:
    - windows
playwright_test_c95876143e123a333ba93099664d4696:
  stage: test
  script:
    - >-
      npx playwright test tests/test6.test.ts
      --output=./reports/report_c95876143e123a333ba93099664d4696.json
  tags:
    - windows
playwright_test_2c67e638ef4801986eff2758b36d6448:
  stage: test
  script:
    - >-
      npx playwright test tests/test7.test.ts
      --output=./reports/report_2c67e638ef4801986eff2758b36d6448.json
  tags:
    - windows
playwright_test_707c45bf8d2d89b99fe5d10d85ff177b:
  stage: test
  script:
    - >-
      npx playwright test tests/test8.test.ts
      --output=./reports/report_707c45bf8d2d89b99fe5d10d85ff177b.json
  tags:
    - windows
